import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/Header'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFacebook, faTwitter } from '@fortawesome/free-brands-svg-icons'
import Link from 'next/link'


export default function Home() {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet"></link>

        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"></link>

      </Head>
      {/* header content */}
      <Header />

      {/* Main Content */}
      <main>
        {/* section one  */}
        <section className=' w-screen h-screen bg-[#add8e6]'>

          <div className='pl-0 md:pl-10 h-full w-full flex items-center flex-col justify-center md:items-start'>

            <div className='text-center md:text-left font-internBold text-8xl md:text-9xl flex w-full flex-col md:flex-row'>
              <div>
                This is a <br />template!
              </div>
              <div className='ml-auto mr-auto'>
                <Link href="/category/all">
                  <button className='text-lg bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl hover:bg-blue-400 outline-black outline p-3 rounded-3xl '>
                    View Products
                  </button>
                </Link>
              </div>
            </div>

            <div className='text-3xl md:text-5xl text-center mt-10'>
              This is just a template and subject to change.
            </div>

            <div className='mt-5 text-lg text-center md:text-left underline underline-offset-4'>
              Coming Soon v3..
            </div>
            <div className='mt-5 text-center md:text-left list-none md:list-disc'>

              <li>Improved Landing page and style with animation</li>
              <li>Crypto payment intergration</li>
              <li>Sign in, sign out dashboard</li>
              <li>Add more prod images of prod via Sanity</li>
            </div>


          </div>
        </section>

      </main>

      {/* footer content */}
      <footer >

      </footer>
    </div >
  )
}
